#Backend Dockerfile
FROM node:18-alpine

WORKDIR /usr/src/app

#copy package files and install dependencies
COPY package*.json ./
RUN npm install

#copy server source code
COPY . . 

EXPOSE 3000

CMD ["node", "server.js"]