#backend dockerfile

FROM node:18-alpine

WORKDIR /usr/src/app

#Copy package files and install dependencies
COPY package.json package-lock.json ./

RUN npm install --omit=dev
#Copy client source code
COPY ./server /usr/src/app/server

WORKDIR /usr/src/app/server
RUN npm run build || echo "No build step needed"
#Expose port
EXPOSE 3000

#Default command to start app
CMD ["node", "src/server.js"]