services:
  client:
    command: npm run build:client && npx serve -s client/dist -l 80
    ports:
      - '80:80'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - client_build:/usr/src/app/client/dist

  server:
    command: npm run build:server && node --experimental-specifier-resolution=node server/dist/server.js
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_NAME=cerberus_production # Override for production
    restart: always
    volumes:
      - server_logs:/usr/src/app/logs

  db:
    env_file:
      - .env.production
    environment:
      - POSTGRES_DB=cerberus_production # Override for production
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    restart: always
    env_file:
      - .env.production
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  postgres_data:
  redis_data:
  client_build:
  server_logs:
