services:
  client:
    image: cerberusproduct/cerberus-auth:client
    ports:
      - '80:80'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - client_build:/usr/src/app/client/dist

  server:
    image: cerberusproduct/cerberus-auth:server
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DB_HOST=db.your-aws-rds-instance.region.rds.amazonaws.com # Point to RDS
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} # Set up Redis
    restart: always
    volumes:
      - redis_data:/data

volumes:
  redis_data:
