services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "
        mkdir -p /usr/src/app/server/src/test
        ln -sf /usr/src/app/server/src/tests/setup.ts /usr/src/app/server/src/test/setup.ts
        npm test
      "
    env_file:
      - .env.test
    environment:
      - NODE_ENV=test
    depends_on:
      - db_test
      - redis_test

  db_test:
    image: postgres:14-alpine
    env_file:
      - .env.test
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cerberus_test
    volumes:
      - ./server/db/schema:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/postgresql/data

  redis_test:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
    tmpfs:
      - /data
