version: '3.8' # WHY?

services:
  # Frontend React application (Vite)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5173:5173' # match your Vite dev server port
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000 #added to connect to backend

  # Backend Node/Express API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000' # Keep original backend port
    depends_on:
      - db
      - redis
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cerberus_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cerberus_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # Redis cache
  redis:
    image: redis:7.2.7
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
  redis_data:
