services:
  client:
    ports:
      - '5173:5173'
    env_file:
      - .env.development

  server:
    ports:
      - '3000:3000'
    env_file:
      - .env.docker.development
    volumes:
      - ./server:/usr/src/app/server:delegated
      - ./client:/usr/src/app/client:delegated

  db:
    ports:
      - '5432:5432'

  redis:
    ports:
      - '6379:6379'
