# fly.toml app configuration file generated for server-falling-wind-1326 on 2025-02-27T04:35:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-falling-wind-1326'
primary_region = 'atl'

[build]
  dockerfile = "Dockerfile"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
